-- CREACIÓN DE LA TABLA PUNTO

CREATE TABLE DOCUMENTO (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    POSICION INT AUTO_INCREMENT,
    IDPUNTO INT,
    NOMBRE VARCHAR(64),
    RUTA VARCHAR(255),
    RUTAWORKINGCOPY VARCHAR(255)
);

ALTER TABLE DOCUMENTO
ADD FOREIGN KEY (IDPUNTO) REFERENCES PUNTO(ID) ON DELETE CASCADE;

-- crear indice en posicion