/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package net.avantic.consejo.gui.panel;

import java.awt.*;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.Optional;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collectors;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import net.avantic.consejo.MainForm;
import net.avantic.consejo.model.Documento;
import net.avantic.consejo.model.Punto;
import net.avantic.consejo.service.DocumentoService;
import net.avantic.consejo.service.PuntoService;

/**
 *
 * @author alexr
 */
public class JPunto extends javax.swing.JPanel {
    
    private MainForm parent;
    
    private Punto punto;
    
    private DocumentoService documentoService;
    
    private PuntoService puntoService;

    /**
     * Creates new form Punto
     */

    public JPunto(MainForm parent, Punto punto, Long position) {
        
        initComponents();
        
        this.parent = parent;
        this.punto = punto;
        
        this.puntoService = new PuntoService();
        this.documentoService = new DocumentoService();

        this.nombreLabel.setText(punto.getNombre());
        this.descripcionLabel.setText(punto.getDescripcion());
        this.jLabel1.setText("#".concat(position.toString()));
        
        this.generaCaratulaCheckBox.setSelected(punto.isGeneraCaratula());
        
        this.documentosPanel.setLayout(new BoxLayout(this.documentosPanel, BoxLayout.Y_AXIS));
        
        this.cargarIconos();

        this.actualizarPanel();
    }
    
    
    private void cargarIconos() {
        
        this.eliminarButton.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete.png")).getImage()
            .getScaledInstance(16, 16, Image.SCALE_SMOOTH))); 
        
        this.subirButton.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/up.png")).getImage()
            .getScaledInstance(16, 16, Image.SCALE_SMOOTH))); 
                
        this.bajarButton.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/down.png")).getImage()
            .getScaledInstance(16, 16, Image.SCALE_SMOOTH))); 
        
        this.editarButton.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/edit.png")).getImage()
            .getScaledInstance(16, 16, Image.SCALE_SMOOTH))); 
        
                final String dir = System.getProperty("user.dir");
        System.out.println("current dir = " + dir);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        guardarDocumentoButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        eliminarButton = new javax.swing.JButton();
        descripcionLabel = new javax.swing.JLabel();
        nombreLabel = new javax.swing.JLabel();
        documentosPanel = new javax.swing.JPanel();
        subirButton = new javax.swing.JButton();
        bajarButton = new javax.swing.JButton();
        editarButton = new javax.swing.JButton();
        generaCaratulaCheckBox = new javax.swing.JCheckBox();

        setBackground(new java.awt.Color(141, 178, 214));
        setMaximumSize(new java.awt.Dimension(32767, 10000));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("#1");

        guardarDocumentoButton.setText("Añadir documento");
        guardarDocumentoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarDocumentoButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Documentos asociados");

        eliminarButton.setBackground(new java.awt.Color(227, 77, 77));
        eliminarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarButtonActionPerformed(evt);
            }
        });

        descripcionLabel.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        descripcionLabel.setText("Descripción");

        nombreLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        nombreLabel.setText("Nombre");

        javax.swing.GroupLayout documentosPanelLayout = new javax.swing.GroupLayout(documentosPanel);
        documentosPanel.setLayout(documentosPanelLayout);
        documentosPanelLayout.setHorizontalGroup(
            documentosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        documentosPanelLayout.setVerticalGroup(
            documentosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        subirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subirButtonActionPerformed(evt);
            }
        });

        bajarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bajarButtonActionPerformed(evt);
            }
        });

        editarButton.setBackground(new java.awt.Color(235, 235, 172));
        editarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarButtonActionPerformed(evt);
            }
        });

        generaCaratulaCheckBox.setText("Genera carátula");
        generaCaratulaCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generaCaratulaCheckBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(documentosPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nombreLabel)
                        .addGap(18, 18, 18)
                        .addComponent(descripcionLabel)
                        .addGap(114, 114, 114)
                        .addComponent(generaCaratulaCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                        .addComponent(subirButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bajarButton)
                        .addGap(55, 55, 55)
                        .addComponent(editarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(eliminarButton)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(guardarDocumentoButton)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(editarButton, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(nombreLabel)
                        .addComponent(descripcionLabel)
                        .addComponent(generaCaratulaCheckBox))
                    .addComponent(eliminarButton, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(subirButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bajarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(guardarDocumentoButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(documentosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void guardarDocumentoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarDocumentoButtonActionPerformed

        JSeleccionarDocumentoModal modal = new JSeleccionarDocumentoModal();
        int seleccion = JOptionPane.showConfirmDialog(this, modal, "Seleccionar Documento", JOptionPane.OK_CANCEL_OPTION);
        
        if (seleccion == 0) {
            try {
                this.documentoService.crearDocumento(this.punto, modal.getNombre(), modal.getRuta());
                this.actualizarPanel();
            } catch (IOException ex) {
                Logger.getLogger(JPunto.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_guardarDocumentoButtonActionPerformed

    private void eliminarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarButtonActionPerformed
        int seleccion = JOptionPane.showConfirmDialog(this, "¿Desea eliminar el punto junto con todos sus documentos asociados?", "Eliminar Punto", JOptionPane.YES_NO_OPTION);
        if (seleccion == 0) {
            this.parent.delete(this.punto);
        }
    }//GEN-LAST:event_eliminarButtonActionPerformed

    private void subirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subirButtonActionPerformed

        this.parent.ordenarSubir(this.punto);
    }//GEN-LAST:event_subirButtonActionPerformed

    private void bajarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bajarButtonActionPerformed
         this.parent.ordenarBajar(this.punto);
    }//GEN-LAST:event_bajarButtonActionPerformed

    private void editarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarButtonActionPerformed
        JEditarPuntoModal modal = new JEditarPuntoModal(this.punto);
        int seleccion = JOptionPane.showConfirmDialog(this, modal, "Editar Punto", JOptionPane.OK_CANCEL_OPTION);
        if (seleccion == 0) {
            this.punto.setNombre(modal.getNombreTextField().getText());
            this.punto.setDescripcion(modal.getDescripcionTextField().getText());
            
            this.nombreLabel.setText(this.punto.getNombre());
            this.descripcionLabel.setText(this.punto.getDescripcion());
            
            this.puntoService.saveOrUpdate(this.punto);
            
        }
    }//GEN-LAST:event_editarButtonActionPerformed

    private void generaCaratulaCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generaCaratulaCheckBoxActionPerformed

        this.punto.setGeneraCaratula(this.generaCaratulaCheckBox.isSelected());
        this.puntoService.saveOrUpdate(this.punto);
    }//GEN-LAST:event_generaCaratulaCheckBoxActionPerformed

 
    private void actualizarPanel() {
        ArrayList<Documento> documentosList = this.obtenerDocumentos();
        this.pintarDocumentos(documentosList);
    }
    
    
    private ArrayList<Documento> obtenerDocumentos() {
        return this.documentoService.listDocumentosByPunto(this.punto).stream()
                .sorted(Comparator.comparingLong(Documento::getPosicion))
                .collect(Collectors.toCollection(ArrayList::new));
        
    }
    
    
    private void pintarDocumentos(ArrayList<Documento> documentosList) {
        
        this.documentosPanel.removeAll();
        int cnt = 0;
        for (Documento documento : documentosList) {
            JDocumentoRow documentoRow = new JDocumentoRow(this, documento);
            if (cnt % 2 == 0) {
                documentoRow.setBackground(new Color(237, 242, 253));
            }
            else {
                documentoRow.setBackground(new Color(218, 228, 251));
            }
            cnt++;
            this.documentosPanel.add(documentoRow);
        }
        
        this.documentosPanel.revalidate();
        this.documentosPanel.repaint();
    }
    
    
    public void eliminarDocumento(Documento documento) {
        this.documentoService.eliminarDocumento(documento);
        this.actualizarPanel();
    }
    
    
    public void reordenarBajarDocumento(Documento documento) {

        Optional<Documento> documentoSiguiente = this.documentoService.listDocumentosByPunto(this.punto).stream()
                .filter(doc -> doc.getPosicion() > documento.getPosicion())
                .sorted(Comparator.comparingLong(Documento::getPosicion))
                .findFirst();
        
        if (!documentoSiguiente.isPresent())
            return;
        
        Long posicion = documento.getPosicion();
        documento.setPosicion(documentoSiguiente.get().getPosicion());
        documentoSiguiente.get().setPosicion(posicion);
         
        this.documentoService.saveOrUpdate(documento);
        this.documentoService.saveOrUpdate(documentoSiguiente.get());

        this.actualizarPanel();
    }
    
        public void reordenarSubirDocumento(Documento documento) {
        Optional<Documento> documentoSiguiente = this.documentoService.listDocumentosByPunto(this.punto).stream()
                .filter(doc -> doc.getPosicion() < documento.getPosicion())
                .sorted((a, b) -> b.getPosicion().compareTo(a.getPosicion()))
                .findFirst();
        
        if (!documentoSiguiente.isPresent())
            return;

        Long posicion = documento.getPosicion();
        documento.setPosicion(documentoSiguiente.get().getPosicion());
        documentoSiguiente.get().setPosicion(posicion);
         
        this.documentoService.saveOrUpdate(documento);
        this.documentoService.saveOrUpdate(documentoSiguiente.get());

        this.actualizarPanel();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bajarButton;
    private javax.swing.JLabel descripcionLabel;
    private javax.swing.JPanel documentosPanel;
    private javax.swing.JButton editarButton;
    private javax.swing.JButton eliminarButton;
    private javax.swing.JCheckBox generaCaratulaCheckBox;
    private javax.swing.JButton guardarDocumentoButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JButton subirButton;
    // End of variables declaration//GEN-END:variables
}
